name: GitHub Context tests
on:
  push:
  workflow_dispatch:
    inputs:
      workflow_input:
        description: Some text
        required: true

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump env
        run: env | sort
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        shell: bash
        run: |
          echo "context: $GITHUB_CONTEXT"

# vim: set ff=unix autoindent ts=2 sw=2 tw=0 et :
