name: Java caching with empty string
on: push

jobs:
  print-context:
    runs-on: ubuntu-latest
    steps:
      - name: Set up java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'liberica'
          cache: ''
      - name: Log notice message
        run:
          echo "::notice title=Testing::Hello \`world\`"

# vim: set ff=unix autoindent ts=2 sw=2 tw=0 et :
