name: Java caching with empty string
on: push

jobs:
  print-context:
    container: ubuntu:latest
    steps:
      - name: Set up java 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'liberica'
          cache: ''

# vim: set ff=unix autoindent ts=2 sw=2 tw=0 et :
