name: Secret workflow
on:
  workflow_dispatch:
    inputs:
      secret:
        description: Some secret text
        required: true

jobs:
  mask-print:
    runs-on: ubuntu-latest
    steps:
      - name: add-mask and print
        run: |
          echo "::add-mask::${{ github.event.inputs.secret }}"
          echo "${{ github.event.inputs.secret }}"
      - name: Print
        run: echo "${{ github.event.inputs.secret }}"

# vim: set ff=unix autoindent ts=2 sw=2 tw=0 et :
