name: Secret workflow
on:
  workflow_dispatch:
    inputs:
      secret:
        description: Some secret text
        required: true

jobs:
  mask-print:
    runs-on: ubuntu-latest
    steps:
      - name: add-mask
        uses: actions/github-script@v6
        with:
          script: |
            core.setSecret(context.payload.inputs.secret);
      - name: Print
        run: echo "${SECRET}"
        env:
          SECRET: ${{ github.event.inputs.secret }}

# vim: set ff=unix autoindent ts=2 sw=2 tw=0 et :
